### ISSUE TITLE
install big sur

### ISSUE THREAD

**Issue by GeekZed** [thinhnpptit/hackintosh-OC-catalina-dell-7566-i5#3]
First of all, Thannnnnnnnks  a lot for your EFI! I just install succesed on my Dell 7566!!! And I'm a noob for hactonish. I want to know  if I can use this EFI to  install  bigsur? Anythings need to upgrade or change?

**Comment by ZedCat** [comment]
BTW , when I fix wifi problem, I found that only things need to do is  install Heliport. Then wifi can work normally.

**Comment by thinhnpptit** [comment]
> First of all, Thannnnnnnnks a lot for your EFI! I just install succesed on my Dell 7566!!! And I'm a noob for hactonish. I want to know if I can use this EFI to install bigsur? Anythings need to upgrade or change?

Yeah, did you trying install bigsur by this EFI, I just have installed catalina, if you did succesed , let me know

**Comment by GeekZed** [comment]
Yeah, I successed on big sur. i just modified alc config on  a similar model dell 7559 . Now everything is good but blueteeth. The problem is when I use blueteeth to connect my blueteeh earphone with wifi on, the sound is intermittent. But with wifi off, everyting is OK.

**Comment by GeekZed** [comment]
I shared docs here  https://github.com/ZedCat/Dell-7566-Hactonish. If you have any problem, I'd like to help :)
